server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order-service/**
    upload-service:
      path: /upload/**
      service: upload-service
      strip-prefix: false
    search-service: /search/**
  sensitive-headers:  # 敏感头,
  add-host-header: true # 添加host头信息

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数,[切换服务重试次数]
  MaxAutoRetries: 0 # 同一实例的重试次数[当前服务重试次数]
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: D:\uploads\key\id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item
