server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.163.131
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  jwt:
    pubKeyPath: D:\uploads\key\id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN